fix the finalizers issue when apply the ownerreference in serviceaccount
chaostoolkit-incubator/kubernetes-crd pull request #60
Opened 2020-07-15 05:59 UTC by hchenxa

fix the issue https://github.com/chaostoolkit-incubator/kubernetes-crd/issues/59

2020-07-17 07:02 UTC, hchenxa commented
cc @dmartin35 please help to review.

2020-10-15 09:17 UTC, dmartin35 commented
sorry for late response, 
I've never used finalizers yet myself, however I can fully understand your permissions modification

Could you however keep only this commit https://github.com/chaostoolkit-incubator/kubernetes-crd/pull/60/commits/43a0ecd08b0c08c2ad7afc285ff499ad54079ced in the PR, 
and remove the one that changes the logs & journal behavior on default command ( this would need to be addressed in another PR ) 

Could you please as well sign-off your commit

Thanks, I'll try to follow more quickly your changes

2020-10-15 09:21 UTC, dmartin35 requested changes
Changes on permissions look fine to me. 
However, could you please keep only this commit in the PR.
And remove the commit that alters the default journal & log from the main command arguments; would require another PR if to be fixed
Thanks

2020-10-15 09:21 UTC, dmartin35 commented on manifests/base/common/configmap.yaml
> +        - --no-log-file
please remove this from this PR, would require another one if to be modified, thanks

2020-10-15 09:21 UTC, dmartin35 commented on manifests/base/common/configmap.yaml
> +        - --journal-path=/tmp/.journal.json
please remove this from this PR, would require another one if to be modified, thanks

2020-10-15 10:37 UTC, hchenxa commented
thanks @dmartin35 comments, already updated and will create another PR for log dir.

2020-10-15 14:18 UTC, merged